config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  namespace :big_o_notation do
    get '/cupcakes', to: 'cupcakes#index'
    get 'cupcakes/index'
    get 'cupcakes/preheat_oven'
    get 'cupcakes/combine_butter_and_sugar'
    get 'cupcakes/add_eggs'
    get 'cupcakes/combine_flour_and_baking_powder'
    get 'cupcakes/combine_milk_flour_and_butter_mixture'
    get 'cupcakes/bake'
    get 'cupcakes/frost'
  end

  namespace :set_theory do
    get '/instagram_account', to: 'instagram_account#index'
    get 'instagram_account/index'
    post 'instagram_account/create'
    get 'instagram_account/intersection'
    get 'instagram_account/union'
    get 'instagram_account/difference'
    get 'instagram_account/relative_complement'
    get 'instagram_account/symmetric_difference'
  end

  namespace :recursion do
    get '/nesting_doll_collection', to: 'nesting_doll_collection#index'
    get 'nesting_doll_collection/index'
    get 'nesting_doll_collection/count'
  end

  namespace :linked_list do
    get '/list', to: 'list#index'
    get 'list/index'
    post 'list/create'
    delete 'list/delete'
  end

  namespace :stack do
    get '/stack', to: 'stack#index'
    get 'stack/index'
    post 'stack/create'
    delete 'stack/delete'
  end

  namespace :queues do
    get '/queue', to: 'queue#index'
    get 'queue/index'
    post 'queue/create'
    delete 'queue/delete'
  end

  namespace :tree do
    get '/tree', to: 'tree#index'
    get 'tree/index'
    get 'tree/harry_worst_iterative'
    get 'tree/harry_worst_recursive'
    get 'tree/harry_best_iterative'
    get 'tree/harry_best_recursive'
    get 'tree/cedric_worst_iterative'
    get 'tree/cedric_worst_recursive'
    get 'tree/cedric_best_iterative'
    get 'tree/cedric_best_recursive'
  end

  namespace :encapsulation do
    get '/horse', to: 'horse#index'
    get 'horse/index'
    get 'horse/move'
  end

  namespace :abstraction do
    get '/remote_control', to: 'remote_control#index'
    get 'remote_control/index'
    get 'remote_control/click_button'
  end

  namespace :inheritance do
    get '/plant', to: 'plant#index'
    get 'plant/index'
    get 'plant/learn'
  end

  namespace :polymorphism do
    get '/craft', to: 'craft#index'
    get 'craft/index'
    get 'craft/create'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'big_o_notation/cupcakes#index'
end

app/models/queues/queue.rb
# frozen_string_literal: true

class Queues::Queue < LinkedList::List
  def enqueue(data)
    add(data)
  end

  def dequeue
    dequeued = head
    update(head: head.next)
    dequeued.update(next: nil)
    dequeued
  end

  def insert(_data, _index)
    raise "Can't insert into the middle of a queue"
  end
end

app/controllers/queues/queue_controller.rb
# frozen_string_literal: true

class Queues::QueueController < ApplicationController
  def index
    @progress = if Queues::Queue.all.empty?
                  'Nobody wants to speak yet :('
                else
                  render_queue(Queues::Queue.all.order(:created_at).last)
                end
  end

  def create
    bof_line = Queues::Queue.all.empty? ? Queues::Queue.create : Queues::Queue.all.order(:created_at).last
    bof_line.enqueue("Person #{DateTime.current}")
    @progress = render_queue(bof_line)
    render :index
  end

  def delete
    bof_line = Queues::Queue.all.order(:created_at).last
    if bof_line.nil? || bof_line.head.nil?
      flash[:error] = '⚠️ Oops! Nothing to delete'
    else
      bof_line.dequeue
    end

    @progress = render_queue(bof_line)
    render :index
  end

  private

  def render_queue(queue)
    template = '<ul>'

    node = queue.head
    until node.nil?
      template += "<li>#{node.data}</li>"
      node = node.next
    end
    template += '</ul>'

    template
  end
end

app/views/queues/queue/index.html.erb
<section class="Screen Screen--yellow">
  <div class="Screen-header">
    <%= image_tag("Feather.png", alt:"Line drawing of a feather", class: "Screen-thumbnail") %>
    <h2>Let's sign up for Birds of a Feather! - Queue example</h2>
  </div>
  <% flash.each do |key, value| %>
    <div class="Alert Alert-<%= key %>"><%= value %></div>
  <% end %>
  <h3>Enqueuing a new item</h3>
  <%= form_with(url: queues_queue_create_path, method: "post", local: true)  do |f| %>
    <%= f.submit 'Get in line' %>
  <% end %>
  <h3>Dequeuing an item</h3>
  <%= form_with(url: queues_queue_delete_path, method: "delete", local: true)  do |f| %>
    <%= f.submit 'Sign up!' %>
  <% end %>
  <h2>Our Birds of a Feather Line</h2>
  <div><%= raw(@progress) %></div>
</section>
<div class="ButtonContainer">
  <%= link_to "Prev", stack_stack_path, class: "Button PrevButton" %>
  <%= link_to "Next", tree_tree_path, class: "Button NextButton" %>
</div>