config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  namespace :big_o_notation do
    get '/cupcakes', to: 'cupcakes#index'
    get 'cupcakes/index'
    get 'cupcakes/preheat_oven'
    get 'cupcakes/combine_butter_and_sugar'
    get 'cupcakes/add_eggs'
    get 'cupcakes/combine_flour_and_baking_powder'
    get 'cupcakes/combine_milk_flour_and_butter_mixture'
    get 'cupcakes/bake'
    get 'cupcakes/frost'
  end

  namespace :set_theory do
    get '/instagram_account', to: 'instagram_account#index'
    get 'instagram_account/index'
    post 'instagram_account/create'
    get 'instagram_account/intersection'
    get 'instagram_account/union'
    get 'instagram_account/difference'
    get 'instagram_account/relative_complement'
    get 'instagram_account/symmetric_difference'
  end

  namespace :recursion do
    get '/nesting_doll_collection', to: 'nesting_doll_collection#index'
    get 'nesting_doll_collection/index'
    get 'nesting_doll_collection/count'
  end

  namespace :linked_list do
    get '/list', to: 'list#index'
    get 'list/index'
    post 'list/create'
    delete 'list/delete'
  end

  namespace :stack do
    get '/stack', to: 'stack#index'
    get 'stack/index'
    post 'stack/create'
    delete 'stack/delete'
  end

  namespace :queues do
    get '/queue', to: 'queue#index'
    get 'queue/index'
    post 'queue/create'
    delete 'queue/delete'
  end

  namespace :tree do
    get '/tree', to: 'tree#index'
    get 'tree/index'
    get 'tree/harry_worst_iterative'
    get 'tree/harry_worst_recursive'
    get 'tree/harry_best_iterative'
    get 'tree/harry_best_recursive'
    get 'tree/cedric_worst_iterative'
    get 'tree/cedric_worst_recursive'
    get 'tree/cedric_best_iterative'
    get 'tree/cedric_best_recursive'
  end

  namespace :encapsulation do
    get '/horse', to: 'horse#index'
    get 'horse/index'
    get 'horse/move'
  end

  namespace :abstraction do
    get '/remote_control', to: 'remote_control#index'
    get 'remote_control/index'
    get 'remote_control/click_button'
  end

  namespace :inheritance do
    get '/plant', to: 'plant#index'
    get 'plant/index'
    get 'plant/learn'
  end

  namespace :polymorphism do
    get '/craft', to: 'craft#index'
    get 'craft/index'
    get 'craft/create'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'big_o_notation/cupcakes#index'
end

app/models/set_theory/instagram_account.rb
# frozen_string_literal: true

class SetTheory::InstagramAccount < ApplicationRecord
  validates_presence_of :account_handle
  validates_length_of :account_handle, maximum: 30
end

app/controllers/set_theory/instagram_account_controller.rb
# frozen_string_literal: true

class SetTheory::InstagramAccountController < ApplicationController
  def index
    @progress = if SetTheory::InstagramAccount.all.empty?
                  "You haven't created anything yet :("
                else
                  "#{dogs}#{cats}"
                end
  end

  def create
    dog = ActiveModel::Type::Boolean.new.cast(account_params[:animal_type_dog])
    cat = ActiveModel::Type::Boolean.new.cast(account_params[:animal_type_cat])
    SetTheory::InstagramAccount.create(account_handle: account_params[:account_handle], dog: dog, cat: cat)
    @progress = "#{dogs}#{cats}"
    render :index
  end

  def intersection
    header = 'Cute accounts that have both cats and dogs!'
    intersection = SetTheory::InstagramAccount.where(dog: true, cat: true)
    render_set(header, intersection)
  end

  def union
    header = 'All the cute accounts!'
    union = SetTheory::InstagramAccount.all
    render_set(header, union)
  end

  def difference
    header = 'Cute accounts that have only dogs (no cats allowed)!'
    difference = SetTheory::InstagramAccount.where(dog: true, cat: false)
    render_set(header, difference)
  end

  def relative_complement
    header = 'Cute accounts that have only cats (no dogs allowed)!'
    complement = SetTheory::InstagramAccount.where(dog: false, cat: true)
    render_set(header, complement)
  end

  def symmetric_difference
    header = 'Cute accounts that have only one type of animal (no cross-species friendships here)!'
    symmetric_difference = SetTheory::InstagramAccount.where(dog: true, cat: false).or(SetTheory::InstagramAccount.where(dog: false, cat: true))
    render_set(header, symmetric_difference)
  end

  private

  def render_set(header, set)
    @progress = if SetTheory::InstagramAccount.all.empty?
                  "You haven't created anything yet :("
                else
                  "#{dogs}#{cats}#{set(header, set)}"
                end
    render :index
  end

  def dogs
    dog_set = SetTheory::InstagramAccount.where(dog: true)
    set('Cute Instagram Dogs', dog_set)
  end

  def cats
    cat_set = SetTheory::InstagramAccount.where(cat: true)
    set('Cute Instagram Cats', cat_set)
  end

  def set(header, calculated_set)
    template = "<div class='Set'><h3>#{header}</h3><ul>"
    template += calculated_set.map { |a| "<li>#{a.account_handle}</li>" }.join
    template += '</ul></div>'
    template
  end

  def account_params
    params.permit(:account_handle, :animal_type_dog, :animal_type_cat, :commit)
  end
end

app/views/set_theory/instagram_account/index.html.erb
<section class="Screen Screen--purple">
  <h2>
    Let's find those cute instagram accounts! - Set theory example
  </h2>
  <h3>Add some accounts to our list</h3>
  <%= form_with(url: set_theory_instagram_account_create_path, method: "post", local: true)  do |f| %>
    <%= f.label "account_handle", "New account" %>
    <%= f.text_field "account_handle", required: true%>
    <fieldset>
      <legend>
        <h3>Choose the type of cute animal(s) featured</h3>
      </legend>
      <div class="Fieldset">
        <div>
          <%= f.label "animal_type_dog", "Dog" %>
          <%= f.check_box "animal_type_dog" %>
        </div>
        <div>
          <%= f.label "animal_type_cat", "Cat" %>
          <%= f.check_box "animal_type_cat" %>
        </div>
      </div>
    </fieldset>
    <%= f.submit 'Add account' %>
  <% end %>
  
  <h3>Let's do some set math</h3>
  <%= link_to "Find the intersection", { action: "intersection" }, class: "Button" %>
  <%= link_to "Find the union", { action: "union" }, class: "Button" %>
  <%= link_to "Find the difference (dogs!)", { action: "difference" }, class: "Button" %>
  <%= link_to "Find the relative complement (cats!)", { action: "relative_complement" }, class: "Button" %>
  <%= link_to "Find the symmetric difference", { action: "symmetric_difference" }, class: "Button" %>
  
  <h2>The Instagram accounts we love</h2>
  <div><%= raw(@progress) %></div>
</section>
<div class="ButtonContainer">
  <%= link_to "Prev", big_o_notation_cupcakes_path, class: "Button PrevButton" %>
  <%= link_to "Next", recursion_nesting_doll_collection_path, class: "Button NextButton" %>
</div>