config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  namespace :big_o_notation do
    get '/cupcakes', to: 'cupcakes#index'
    get 'cupcakes/index'
    get 'cupcakes/preheat_oven'
    get 'cupcakes/combine_butter_and_sugar'
    get 'cupcakes/add_eggs'
    get 'cupcakes/combine_flour_and_baking_powder'
    get 'cupcakes/combine_milk_flour_and_butter_mixture'
    get 'cupcakes/bake'
    get 'cupcakes/frost'
  end

  namespace :set_theory do
    get '/instagram_account', to: 'instagram_account#index'
    get 'instagram_account/index'
    post 'instagram_account/create'
    get 'instagram_account/intersection'
    get 'instagram_account/union'
    get 'instagram_account/difference'
    get 'instagram_account/relative_complement'
    get 'instagram_account/symmetric_difference'
  end

  namespace :recursion do
    get '/nesting_doll_collection', to: 'nesting_doll_collection#index'
    get 'nesting_doll_collection/index'
    get 'nesting_doll_collection/count'
  end

  namespace :linked_list do
    get '/list', to: 'list#index'
    get 'list/index'
    post 'list/create'
    delete 'list/delete'
  end

  namespace :stack do
    get '/stack', to: 'stack#index'
    get 'stack/index'
    post 'stack/create'
    delete 'stack/delete'
  end

  namespace :queues do
    get '/queue', to: 'queue#index'
    get 'queue/index'
    post 'queue/create'
    delete 'queue/delete'
  end

  namespace :tree do
    get '/tree', to: 'tree#index'
    get 'tree/index'
    get 'tree/harry_worst_iterative'
    get 'tree/harry_worst_recursive'
    get 'tree/harry_best_iterative'
    get 'tree/harry_best_recursive'
    get 'tree/cedric_worst_iterative'
    get 'tree/cedric_worst_recursive'
    get 'tree/cedric_best_iterative'
    get 'tree/cedric_best_recursive'
  end

  namespace :encapsulation do
    get '/horse', to: 'horse#index'
    get 'horse/index'
    get 'horse/move'
  end

  namespace :abstraction do
    get '/remote_control', to: 'remote_control#index'
    get 'remote_control/index'
    get 'remote_control/click_button'
  end

  namespace :inheritance do
    get '/plant', to: 'plant#index'
    get 'plant/index'
    get 'plant/learn'
  end

  namespace :polymorphism do
    get '/craft', to: 'craft#index'
    get 'craft/index'
    get 'craft/create'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'big_o_notation/cupcakes#index'
end

app/models/polymorphism/crocheting.rb
# frozen_string_literal: true

class Polymorphism::Crocheting
  attr_reader :row_length, :tool

  def initialize(row_length)
    @row_length = row_length
    @tool = '1 hook'
  end

  def create_fabric(number_of_rows)
    raise 'Must specify a number of rows to create your fabric.' unless number_of_rows&.is_a?(Integer)

    fabric = []
    number_of_rows.times do
      fabric << stitch_row
    end

    fabric
  end

  private

  def stitch_row
    row = ''
    row_length.times do
      row += single_crochet
    end

    row += "Turn.\n"
    row
  end

  def single_crochet
    'Created a single crochet stitch; '
  end
end

app/models/polymorphism/knitting.rb
# frozen_string_literal: true

class Polymorphism::Knitting
  module Stitch
    KNIT = 'knit'
    PURL = 'purl'
  end

  attr_reader :row_length, :tool

  def initialize(row_length)
    @row_length = row_length
    @tool = '2 needles'
  end

  def create_fabric(number_of_rows)
    raise 'Must specify a number of rows to create your fabric.' unless number_of_rows&.is_a?(Integer)

    fabric = []
    number_of_rows.times do |row|
      fabric << if row.even?
                  stitch_row(Stitch::KNIT)
                else
                  stitch_row(Stitch::PURL)
                end
    end

    fabric
  end

  private

  def stitch_row(stitch)
    row = ''
    row_length.times do
      row += send(stitch)
    end

    row += "Turn.\n"
    row
  end

  def knit
    'Created a knit stitch; '
  end

  def purl
    'Created a purl stitch; '
  end
end

app/models/polymorphism/weaving.rb
# frozen_string_literal: true

class Polymorphism::Weaving
  attr_reader :row_length, :tool

  def initialize(row_length)
    @row_length = row_length
    @tool = 'Loom and shuttle'
  end

  def create_fabric(number_of_rows)
    raise 'Must specify a number of rows to create your fabric.' unless number_of_rows&.is_a?(Integer)

    fabric = []
    number_of_rows.times do |row|
      fabric << weave_row(row)
    end

    fabric
  end

  private

  def weave_row(row_number)
    row = ''

    # start with Over when rowNumber is even, then every even stitch
    # start with Under when rowNumber is odd, then every even stitch
    row_length.times do |stitch_number|
      row += if (row_number.even? && stitch_number.even?) || (row_number.odd? && stitch_number.odd?)
               weave_weft_over_warp
             else
               weave_weft_under_warp
             end
    end

    row += "Turn.\n"
    row
  end

  def weave_weft_under_warp
    'Weft thread under the warp; '
  end

  def weave_weft_over_warp
    'Weft thread over the warp; '
  end
end

app/controllers/polymorphism/craft_controller.rb
# frozen_string_literal: true

class Polymorphism::CraftController < ApplicationController
  def index
    @progress = "You haven't created anything yet :("
  end

  def create
    unless craft_params.key?(:craft)
      flash[:error] = '⚠️ Oops! Pick a craft'
      render :index
      return
    end

    yarn_craft = if craft_params[:craft] == 'knit'
                   Polymorphism::Knitting
                 elsif craft_params[:craft] == 'crochet'
                   Polymorphism::Crocheting
                 elsif craft_params[:craft] == 'weave'
                   Polymorphism::Weaving
                 end

    chosen_craft = yarn_craft.new(craft_params[:row_length].to_i)
    fabric = chosen_craft.create_fabric(craft_params[:number_of_rows].to_i)
    @progress = fabric.join('<br/>')

    render :index
  end

  private

  def craft_params
    params.permit(:craft, :row_length, :number_of_rows, :commit)
  end
end

app/views/polymorphism/craft/index.html.erb
<section class="Screen Screen--red">
  <div class="Screen-header">
    <%= image_tag("YarnCrafts.png", alt:"Line drawing of common yarn crafts", class: "Screen-thumbnail") %>
    <h2>Let's craft! - Polymorphism example</h2>
  </div>
  <% flash.each do |key, value| %>
    <div class="Alert Alert-<%= key %>"><%= value %></div>
  <% end %>
  <%= form_with(url: polymorphism_craft_create_path, method: "get", local: true)  do |f| %>
    <fieldset>
      <legend><h3>Choose your favorite yarn craft</h3></legend>
      <div class="Fieldset">
        <div>
          <%= f.label "knit", "Knitting" %>
          <%= f.radio_button "craft", "knit" %>
        </div>
        <div>
          <%= f.label "crochet", "Crocheting" %>
          <%= f.radio_button "craft", "crochet" %>
        </div>
        <div>
          <%= f.label "weave", "Weaving" %>
          <%= f.radio_button "craft", "weave" %>
        </div>
      </div>
    </fieldset>
    <%= f.label "row_length", "Row length" %>
    <%= f.number_field 'row_length', required: true %>
    <%= f.label "number_of_rows", "Number of rows" %>
    <%= f.number_field 'number_of_rows', required: true %>
    <div>
      <%= f.submit 'Create my fabric!' %>
    </div>
  <% end %>
  
  <h2>Our Fabric</h2>
  <div><%= raw(@progress) %></div>
</section>
<div class="ButtonContainer">
  <%= link_to "Prev", inheritance_plant_path, class: "Button PrevButton" %>
  <a class="Button NextButton" disabled="disabled" href="">Next</a>
</div>